# Generated by Django 3.0.3 on 2020-09-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.URLField()),
                ('Line', models.PositiveIntegerField(default=5)),
            ],
        ),
    ]
