# Generated by Django 3.0.3 on 2020-09-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='Line',
            new_name='Number_of_Lines',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='link_name',
            new_name='URL_of_website',
        ),
    ]
